### ISSUE TITLE
Refactor math handling to accomodate latest pandoc version (2.10 not available for osx-arm64)

### ISSUE THREAD

**Issue by icct-galvarez** [theicct/roadmap-doc#4]
Currently, our user guide states that pandoc 2.10 should be obtained. However, the earliest [pandoc version](https://anaconda.org/conda-forge/pandoc/files?page=1) built for Mac Silicon machines is 2.19, but that caused a `Bad CPU type in executable` error. when running `copy_doc.sh`.  So I went ahead and grabbed the latest version of pandoc (3.5), but it causes issues with some of the equations when I try to serve locally with jekyll:

```
/Users/g.alvarez/.gem/ruby/3.3.5/gems/liquid-4.0.4/lib/liquid/block_body.rb:136:in `raise_missing_variable_terminator': Liquid syntax error (line 414): Variable '{{EF}' was not properly terminated with regexp: /\}\}/ (Liquid::SyntaxError)
...
/Users/g.alvarez/.gem/ruby/3.3.5/gems/liquid-4.0.4/lib/liquid/block_body.rb:136:in `raise_missing_variable_terminator': Liquid syntax error (line 446): Variable '{{MW}' was not properly terminated with regexp: /\}\}/ (Liquid::SyntaxError)
```

Looks like many equations are now rendered with:

![Screenshot 2024-10-11 at 12 50 38 PM](https://github.com/user-attachments/assets/3ea8546d-cfca-4692-a7a5-3920945996bb)

whereas it used to be:

![Screenshot 2024-10-11 at 12 50 51 PM](https://github.com/user-attachments/assets/402a3f0a-f87b-479d-b3c6-910af71d903e)

So the `doc_to_page.fix_math()` function might be out-dated. But even if I swap all those over to the `$$ ... $$` format, I resolve the EF error but still get the same liquid syntax error for MW.

**Comment by icct-galvarez** [comment]
Ah, if I use pandoc 3.1.2 (the next version after the buggy 2.19), the output contains no `math` tags, and I get around the bad CPU issue, but I still get the syntax errors.

**Comment by icct-galvarez** [comment]
For now, I'm working around it by manually copying over the text from v2.5 for the three problematic equations. Here's the syntax from 2.5 that does not cause any errors:

```
$$\text{EF}_{Ch\text{ina},\ \ \text{AltFuel}} = \frac{\text{EF}_{\text{Euro},\ \text{AltFuel}}}{\text{EF}_{\text{Euro},\ \text{ICE}}}\  \times \ \text{EF}_{Ch\text{ina},\ \text{ICE}}$$

...

$$\text{SO}_{2}\left( g \right) = \ \text{FC}\left( g \right)\  \times \ \lbrack S\rbrack\left( \text{ppm} \right) \times \ \frac{\text{MW}_{\text{SO}_{2}}\ }{\text{MW}_{S}}\  \times \ f\text{SO}_{2}\  \times \ \left( \frac{10^{6}}{\text{ppm}} \right)$$

...

- \\(\frac{\text{MW}\_{\text{SO}\_{2}}\ }{\text{MW}\_{S}}\\) = the ratio of molecular weight of sulfur dioxide to sulfur = 2.0
```

**Comment by icct-jbenoit** [comment]
Confirmed that I used the same manual workaround when publishing the v2.11 documentation. Thanks documenting the details here, was very helpful!

**Comment by icct-galvarez** [comment]
@icct-jbenoit will add some notes here regarding our discussion on how to adjust math handling to bring our pandoc dependency up to date, both for Roadmap and the soon-to-be-created JETSTREAM public docs. Thanks!

**Comment by icct-jbenoit** [comment]
We discussed an approach towards debugging:
- Check Pandoc documentation/version history to understand what changes occurred between 2.10 and 2.19 to cause the bug
- The issue is with with the `fix_math` function during the conversion in `doc_to_page.py`. The script was written assuming an output type from Pandoc v2.10 version. We had to update to 2.19 (the oldest version possible) to run Pandoc on our machines. The function will still run now but won't properly format the equations.

```py
def fix_math(doc):
    """Fix how mathjax escapes work with markdown/jekyll."""
    for i, l in enumerate(doc):
        if r"\(" in l:
            l = _fix_inline(l)
        l = l.replace(r"\[", r"$$")
        l = l.replace(r"\]", r"$$")  # display math
        l = l.replace(r"AFLEET\ Ratio", "AFLEET Ratio")  # HACK: hard fix for this case
        doc[i] = l

    return doc
```
- Best approach is to debug using a small test Markdown file with an equation
- Pandoc is at 3.7.0 now, we should try to update to the latest version if possible. It would be good to understand the 3.0 breaking change first
